[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "qspice-qraw-viewer"
version = "0.1.0"
description = "QSPICE QRAW Waveform Viewer"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "PySide6>=6.7",
    "jupyterlab",
    "matplotlib",
]

[project.scripts]
qspice-qraw-viewer = "viewer.__main__:main"

[tool.setuptools.packages.find]
include = ["viewer*"]

[tool.setuptools.package-data]
viewer = ["*.qml", "resources/*.svg", "resources/*.png", "resources/*.ico"]

[tool.pyside6-project]
files = ["main.py"]
